apiVersion: apps/v1
kind: Deployment
metadata:
  name: rds-springboot-app
  labels:
    app: rds-springboot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rds-springboot-app
  template:
    metadata:
      labels:
        app: rds-springboot-app
    spec:
      containers:
      - name: rds-springboot-app
        image: 383053847833.dkr.ecr.ap-south-1.amazonaws.com/rdsproject:1.0
        ports:
        - containerPort: 8080
