spring.datasource.url=jdbc:postgresql://aurora-postgres-cluster.cluster-czpjhxjfnlpf.ap-south-1.rds.amazonaws.com:5432/companydb
spring.datasource.username=auroradbadmin
spring.datasource.password=Password123!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
